<?php
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";
require_once "kegiatanmenujs.phtml";
$referensi = Menu_Service::getInstance();
$referensi = Kegiatan_Service::getInstance();

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
		
$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;
 $tgl_sekarang=date ("Y-m-d"); 
?>

<div class="navlink">
<a href="#" class="home" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/home');">Halaman Utama</a>
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">Program Kegiatan</h2>
		<div class="search-panel">
			<form method="post" id="frmCariKegiatan" name="frmCariKegiatan">Kata Kunci :
				<?
				$kategoriCari = array("NamaKegiatan" => "Kegiatan",  "KodeKegiatan" => "Kode Kegiatan");
										
				echo $ctrlFrm->formSelect('kategoriCari', $this->kategoriCari, null, $kategoriCari);						
				?>
				<input type="text" name="carii">
				<?
			         $atribSubmit = array("onclick"=>"javascript:cariKegiatan();");
			         echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
				?>
			</form>
		</div>
		<div class="space-line"></div>		
		<fieldset class="fields"> 
			<div class="spacer"> </div>
			<? 
			
			$status = $this->hasil;
			$proses = $this->proses;
			$keterangan = $this->keterangan;
			
			$pesan->show_message($proses, $keterangan, "$status" ); ?>
			<div class="spacer"> </div>	
			
			<div class="add" title="Tambah Data" onClick="KegiatanForm('insert','');"></div> 
			<div class="blank"></div>
			<table id="sorter" class="sortable" cellspacing="1" cellpadding="2" border="0" align="center">
				<th width=2.5%  class="nosort">No</th> 
				<th width=2.5% class="sorted order2 sortable">Kode Kegiatan</th> 
				<th width=17.5% class="sorted order2 sortable">Kegiatan</th> 
				<th width=12% class="sorted order2 sortable">Jadwal</th> 
				<th width=12.5% class="sorted order2 sortable">Instansi</th> 
				<th width=4% class="sorted order2 sortable">Komponen</th> 
				<th width=4% class="sorted order2 sortable">Komponen Sub</th> 
				<th width=4% class="sorted order2 sortable">Komponen Sub Detail</th> 
				<th width=15% class="sorted order2 sortable">Anggaran</th> 
				<th width=5% colspan="3"  class="nosort">Tindakan</th>
				
				<?php
					if (count($this->kegiatanMenu) == 0){ 
				?>
					<tr class="event2"><td colspan="10"><font color="red">Data Tidak Ditemukan</font></td></tr>
				<?} else {					
					foreach ($this->kegiatanMenu as $key => $val): 
					if ($key%2==0) { ?>
						<tr class="event">
					<? } else if ($key%2==1) { ?>
						<tr class="event2">
					<? } 
					$KodeKegiatan = $this->escape($val['KodeKegiatan']); 
					$NamaKegiatan = $this->escape($val['NamaKegiatan']); 
					$JadwalAwal = $this->escape($val['JadwalAwal']); 
					$Instansi = $this->escape($val['Instansi']); 				
					$KodeKomponen = $this->escape($val['KodeKomponen']); 				
					$KodeSubKomponen = $this->escape($val['KodeSubKomponen']); 				
					$KodeDetailSubKomponen = $this->escape($val['KodeDetailSubKomponen']); 				
					$Anggaran = $this->escape($val['Anggaran']); 		
					$JadwalAkhir = $this->escape($val['JadwalAkhir']); 
					
					if($tgl_sekarang>$JadwalAkhir){ ?>
						<tr class="selesai">
					<? }  
					$JadwalAwal=date("d M Y", strtotime($JadwalAwal));
					$JadwalAkhir=date("d M Y", strtotime($JadwalAkhir));
							
					$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;	
					
					
					
					?>
					
					<td class="clcenter"><? echo $noUrut;?>&nbsp;&nbsp;</td>
					<td class="clleft">&nbsp;<? echo $KodeKegiatan;?></td>
					<td class="clleft">&nbsp;<? echo $NamaKegiatan;?></td>
					<td class="clcenter">&nbsp;<? echo $JadwalAwal;?> s.d <? echo $JadwalAkhir;?></td>										
					<td class="clleft">&nbsp;<? echo $Instansi;?></td>										
					<td class="clcenter">&nbsp;<? echo $KodeKomponen;?></td>										
					<td class="clcenter">&nbsp;<? echo $KodeSubKomponen;?></td>										
					<td class="clcenter">&nbsp;<? echo $KodeDetailSubKomponen;?></td>										
					<td class="clleft">&nbsp;Rp. <? echo number_format($Anggaran, 0, ',', '.');?></td>										
					<td><div onClick="PenerimaForm('<? echo $KodeKegiatan;?>');" class="view" title="Lihat Penerima"></div></td>
					<td><div onClick="KegiatanForm('update','<? echo $KodeKegiatan;?>');" class="edit" title="Ubah Data"></div></td>
					<td><div class="delete" title="Hapus Data" onClick="Kegiatanhapus('KodeKegiatan', '<? echo $KodeKegiatan; ?>')" ></td>
					</tr>
					<?
					endforeach;
				}
				?>
			</table>
			<?	
			$totalData = $this->totKegiatan;
			$modul = $this->basePath."/kegiatan/kegiatan/kegiatanmenu";			
			echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $param1, $param2, $param3, $param4);		
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>
