<?php
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";
require_once "kegiatanmenujs.phtml";
$referensi = Menu_Service::getInstance();
$referensi = Kegiatan_Service::getInstance();

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
		
$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

   $jmldata = count($this->namaPenduduk);
   for ($j = 0; $j < $jmldata; $j++) {
		$datalist[$j] = array("NIK" =>(string)$this->namaPenduduk[$j]['NIK'],								
				      "NamaLengkap" =>(string)$this->namaPenduduk[$j]['NamaLengkap'],
				      "Alamat" =>(string)$this->namaPenduduk[$j]['Alamat'],
				      "RT" =>(string)$this->namaPenduduk[$j]['RT'],
				      "RW" =>(string)$this->namaPenduduk[$j]['RW'],
				      "Dusun" =>(string)$this->namaPenduduk[$j]['Dusun'],
				      "KodePos" =>(string)$this->namaPenduduk[$j]['KodePos'],
				      "JK" =>(string)$this->namaPenduduk[$j]['JK'],
				      "TempatLahir" =>(string)$this->namaPenduduk[$j]['TempatLahir'],
				      "TglLahir" =>(string)$this->namaPenduduk[$j]['TglLahir'],
				      "NoAkta" =>(string)$this->namaPenduduk[$j]['NoAkta'],
				      "GolDarah" =>(string)$this->namaPenduduk[$j]['GolDarah'],
				      "Agama" =>(string)$this->namaPenduduk[$j]['Agama'],
				      "Pekerjaan" =>(string)$this->namaPenduduk[$j]['Pekerjaan'],
				      "NamaIbu" =>(string)$this->namaPenduduk[$j]['NamaIbu'],
				      "NamaAyah" =>(string)$this->namaPenduduk[$j]['NamaAyah'],
				      "Status" =>(string)$this->namaPenduduk[$j]['Status'],
				      "Kelurahan" =>(string)$this->namaPenduduk[$j]['Kelurahan']								
				);
		}  

$par=$this->par;	
?>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Popup</title>
<link href="<? echo $this->basePath;?>/css/tools.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<? echo $this->basePath;?>/css/thickbox.css" type="text/css" media="screen" />
<link href="<? echo $this->basePath;?>/css/main.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<? echo $this->basePath;?>/css/style.css" type="text/css" title="Nice Blue style" />
<SCRIPT src="<? echo $this->basePath;?>/js/jquery.js" type="text/javascript"></SCRIPT>
<SCRIPT src="<? echo $this->basePath;?>/js/jquery.form.js" type="text/javascript"></SCRIPT>
</head>

<body>
<div class="popups" >
<div class="space-line"></div>
<div id="tableview">
<div class="blank"></div>
	<h3 class="title">Daftar Penduduk PPLS </h3>

	<table  border="0" cellspacing="1" cellpadding="2" class="tbl2" id="std">
		<tr>
			<td>NIK :</td>
			<td>
				<input type="text" id="NIK" name="NIK" value="<?php echo $this->NIK?>">
				<input type="button" id="cari" name="cari" value="Cari" onClick="cariPenduduk();">
			</td>
		</tr>
	</table>
		
<fieldset class="fields"> 
	<table  align="center" border="0" cellspacing="1" cellpadding="2" class="tbl">
		    <th width=5%>No</th>
			<th width=10%>NIK</th>
		    <th width=25%>Nama</th>
		    <th width=35%>Alamat</th>
			<th width=10%>Status</th> 
			<th width=15%>Kelurahan</th>
<?
			if($jmldata == 0){
				echo '<tr class="event">
						<td><font color=\"red\">-</font></td>								
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						</tr>';
			}else{ 			  			  
				$j=1;	$no=0;
				$x=0;
				foreach ($datalist as $key => $val):
				$no = (($currentPage -1)* $numToDisplay) + $key +1;						
				if ($key%2==0) { ?>
					<tr class="event">
					  <?php } else if ($key%2==1) { ?>
					<tr class="event2">
					  <?php } ?>		  
					<td class="clcenter"><?php echo $no;?></td>					
					<td class="cljustify">
						<a class="enclose" href='#' onclick="PilihanData('<? echo $this->escape($val['NIK']); ?>','<? echo $this->escape($val['NamaLengkap']);  ?>','<? echo $this->escape($val['Alamat']);  ?>','<? echo $this->escape($val['Status']);  ?>','<? echo $this->escape($val['Kelurahan']);  ?>')">
						<?php 
						echo $this->escape($val['NIK']);
						?></a>
					</td>			
					<td class="clleft">
						<?php echo $this->escape($val['NamaLengkap']);?>	
					</td>
					<td class="cllefts">
						<?php echo $this->escape($val['Alamat']);?>
					</td>
					<td class="clcenter">
						<?php echo $this->escape($val['Status']);	?>
					</td>
					<td class="clleft">
						<?php echo $this->escape($val['Kelurahan']);?>
					</td>
				</tr>
			 <?php $i++; $x++;
			endforeach; 
			  }
			 ?>	
		</table>
		</fieldset>
		<fieldset class="fields1" >	
			<input type="button" onclick="window.close()" value="Tutup"/>
		</fieldset>		
</div>
</div>
</body>
</html>
