<?php
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";
require_once "rekapmenujs.phtml";
$referensi = Rekap_Service::getInstance();
$referensi = Kegiatan_Service::getInstance();

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
		
$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>

<div class="navlink">
<a href="#" class="home" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/home');">Halaman Utama</a>
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">Rekap Kelurahan</h2>
		
		<div class="space-line"></div>	
		<fieldset class="fields"> 
			<div class="spacer"> </div>
			<form method="post" id="frmRekapKelurahan" name="frmRekapKelurahan">
				
				Kelurahan :
				<?
					$jmlKelList = count($this->kelList);
					$kelList['-'] = '--Pilih--';
					for ($i = 0; $i < $jmlKelList; $i++) {
						$kelList[$this->kelList[$i]->Kelurahan] = (string)$this->kelList[$i]->Kelurahan;			 
					}					
					$kelAtrib = array("id"=>"Kelurahan", "tabindex"=>"17");
					echo $ctrlFrm->formSelect('Kelurahan',$this->rekapkelMenu['Kelurahan'], $kelAtrib, $kelList);
				?>
				<br />
				<?
			        $atribSubmit = array("onclick"=>"javascript:return rekapKelurahan();");
			        echo $ctrlFrm->formSubmit('cetak', 'Cetak', $atribSubmit)."&nbsp;";
					
				?>
			</form>
		</fieldset>		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>