<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">Tambah Data Propinsi</h2>
	    <div class="spacer"></div> 
		
		<?
		if(strtolower($this->jenisForm) == 'insert') {	$namaForm = 'frmtambahpropinsi'; }
			else if (strtolower($this->jenisForm) == 'update') {	$namaForm = 'frmubahpropinsi'; }
			else {	$namaForm = 'frmhapuspropinsi'; }
		
		?>
		<form method="post" name="<? echo $namaForm;?>" id="<? echo $namaForm;?>">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
				    <td align="right" width="180">* Propinsi :</td>
					<td>
						<?
						$n_propinsiAttrib = array("size" => 50,"maxlength" => 50);
						echo $ctrlFrm->formText('n_propinsi', $this->detailPropinsi['n_propinsi'], $n_propinsiAttrib);
						?>
						
					</td>
				</tr>
				<tr>
				    <td align="right" width="180">* Kode Propinsi :</td>
					<td>
						<?
						$c_propinsiAttrib = array("size" => 50,"maxlength" => 50);
						echo $ctrlFrm->formText('c_propinsi', $this->detailPropinsi['c_propinsi'], $c_propinsiAttrib);
						echo $ctrlFrm->formHidden('id', $this->detailPropinsi['id'], null);
						
						?>
						
					</td>
				</tr>
				<tr>
				    <td></td>
				    <td>
						<div class="right">
							<input type="button" value="Batal" onClick="propinsilist();"> 
							<input type="reset" value="Ulangi"> 
							<input   type="submit" value="Simpan">
						</div>
					</td>
				</tr>
				<tr>
				    <td>* Harus Diisi</td>
				    <td></td>
				</tr>
			</table>
		</form>
	</div>
</div>