<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();

$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">Propinsi</h2>
		<div class="search-panel">
			<form method="post" id="frmcaripropinsi" name="frmcaripropinsi">Kata Kunci :
				<input type="text" name="carii" value="<? echo $this->katakunciCari; ?>">
				<?
			         $atribSubmit = array("onclick"=>"javascript:caripropinsi();");
			         echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
				?>
			</form>
		</div>
		<div class="space-line"></div>

		
		<fieldset class="fields"> 
			<div class="spacer"> </div>
			<? 
			
			$status = $this->hasil;
			$proses = $this->proses;
			$keterangan = $this->keterangan;
			
			$pesan->show_message($proses, $keterangan, "$status" ); ?>
			<div class="spacer"> </div>	
			
			<div class="add" title="Tambah Data" onClick="propinsiForm('insert','');"></div> 

			<div class="blank"></div>
			
			
			<table id="sorter" class="sortable" cellspacing="1" cellpadding="2" border="0" align="center">
				<th width=5% class="nosort">No</th> 
				<th width=10%>Kode</th>
				<th width=75%>Propinsi</th> 
				<th width=10% colspan="2" class="nosort">Tindakan</th>
				
				<?
				if (count($this->propinsiList) == 0){ 
				?>
					<tr class="event2"><td colspan="5"><font color="red">Data Tidak Ditemukan</font></td></tr>
				<?} else {
						
						
						foreach ($this->propinsiList as $key => $val): 
						if ($key%2==0) { ?>
							<tr class="event">
						<? } else if ($key%2==1) { ?>
							<tr class="event2">
						<? } 
						$id = $this->escape($val['id']); 
						$n_propinsi = $this->escape($val['n_propinsi']); 
						$c_propinsi = $this->escape($val['c_propinsi']); 
						$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
						
						// form Hidden 
						echo $ctrlFrm->formHidden('id', $id, null);
						
						?>
						
						<td class="clcenter"><? echo $noUrut;?></td>
						<td class="clcenter"><? echo $c_propinsi;?></td>
						<td class="clleft">&nbsp;<? echo $n_propinsi;?></td>
						
						<td><div onClick="propinsiForm('update','<? echo $id;?>');" class="edit" title="Ubah Data"></div></td>
						<td><div class="delete" title="Hapus Data" onClick="propinsiHapus('Propinsi', '<? echo $id; ?>')" ></td>
						
					
						</tr>
					<?
					endforeach;
				}
				?>
			</table>

			<?	
			$totalData = $this->totPropinsiList;
			$fungsi = 'propinsilist';
			$modul = $this->basePath."/adm/propinsi/propinsilist";
			echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $this->katakunciCari, $param2, $param3, $param4);		
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>