<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();

$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>
<script type="text/javascript">
	$(function() {
		$("#tglawalkrs").datepicker();
		$("#tglakhirkrs").datepicker();
		$("#tglawalisidatamhs").datepicker();
		$("#tglakhirisidatamhs").datepicker();
	});
</script>

	
<div class="navlink">
	<a  href="index_login.php">Halaman Utama</a> <strong> &#8250; </strong> <a href="#">Variabel</a>
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">Variabel</h2>
		<div class="search-panel">
			<form method="post" id="frmcaripropinsi" name="frmcaripropinsi">Kata Kunci :
				<input type="text" name="carii" value="<? echo $this->katakunciCari; ?>">
				<?
			         $atribSubmit = array("onclick"=>"javascript:caripropinsi();");
			         echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
				?>
			</form>
		</div>
		<div class="space-line"></div>

<? 
$pesancek=$this->pesancek;
if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<div id="top"></div>	
	<div id="confirm" class="<?=$confirm?>" style="display: none">
		<?echo $pesan = $this->pesan;?>
	</div>			
	<div class="space-line"></div>
	
		<fieldset class="fields"> 
			<div class="spacer"> </div>
			<? 
			
			$status = $this->hasil;
			$proses = $this->proses;
			$keterangan = $this->keterangan;
			
			//$pesan->show_message($proses, $keterangan, "$status" ); ?>
			<div class="spacer"> </div>	
			

			<div class="blank"></div>
			
			
			<table id="sorter" class="sortable" cellspacing="1" cellpadding="2" border="0" align="center">
				<th width=5% class="nosort">No</th> 
				<th width=20%>Kode</th>
				<th width=50%>Variabel</th> 
				<th width=10%  class="nosort">Ubah</th>
				
				<?
				if (count($this->sesiList) == 0){ 
				?>
					<tr class="event2"><td colspan="5"><font color="red">Data Tidak Ditemukan</font></td></tr>
				<?} else {
						
						
						foreach ($this->sesiList as $key => $val): 
						if ($key%2==0) { ?>
							<tr class="event">
						<? } else if ($key%2==1) { ?>
							<tr class="event2">
						<? } 
						$id = $this->escape($val['id']); 
						$n_var = $this->escape($val['n_var']); 
						$c_var = $this->escape($val['c_var']); 
						$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
						echo $ctrlFrm->formHidden('id', $id, null);	
						echo $ctrlFrm->formHidden('c_var', $c_var, null);	
						?>
						
						<td class="clcenter"><? echo $noUrut;?></td>
						<td class="clleft">
						<? 
						
						if ($c_var=='smt_curr'){if(trim($n_var) == '1'){$n_var = 'Ganjil';}if(trim($n_var) == '2'){$n_var = 'Genap';}echo "Semester";}
						if ($c_var=='thn_curr'){echo "Tahun Ajaran";}
						if ($c_var=='tglawalkrs'){echo "Tanggal Awal KRS";}
						if ($c_var=='tglakhirkrs'){echo "Tanggal Akhir KRS";}
						if ($c_var=='tglawalisidatamhs'){echo "Tanggal Awal Isi Biodata Mahasiswa";}
						if ($c_var=='tglakhirisidatamhs'){echo "Tanggal Akhir Isi Biodata Mahasiswa";}						
						?>
						</td>
						<td class="clleft">&nbsp;
						<? 
						echo $n_var;
						// if ($c_var=='thn_curr'){echo '<input type="text" class="text"  name="thn_cur" id="thn_cur" value="'.trim($n_var).'" size="10" maxlength="500"/>';}
						// if ($c_var=='smt_curr'){
												// $c_semester_List = array(
																		// ""=>"--Pilih--",
																		// "1"=>"1",
																		// "2"=>"2");
												// echo $ctrlFrm->formSelect('c_semester', $c_semester, null, $c_semester_List);
						// }
						// if ($c_var=='tglawalkrs'){						
						// echo '<input type="text" readonly="true" name="tglawalkrs" id="tglawalkrs" size="10" value="'.trim($n_var).'" >';						
						// }
						// if ($c_var=='tglakhirkrs'){echo '<input type="text" readonly="true" name="tglakhirkrs" id="tglakhirkrs" size="10" value="'.trim($n_var).'" >';}
						// if ($c_var=='tglawalisidatamhs'){echo '<input type="text" readonly="true" name="tglawalisidatamhs" id="tglawalisidatamhs" size="10" value="'.trim($n_var).'" >';}
						// if ($c_var=='tglakhirisidatamhs'){echo '<input type="text" readonly="true" name="tglakhirisidatamhs" id="tglakhirisidatamhs" size="10" value="'.trim($n_var).'" >';}							
						
						?>
						</td>						
						<td><div onClick="ubahvariabel('update','<? echo $id;?>');" class="edit" title="Ubah Data"></div></td>
						<!--<td><div class="delete" title="Hapus Data" onClick="hapusvariabel('<? //echo $c_var; ?>', '<? //echo $id; ?>')" ></td>-->
						</tr>
					<?
					endforeach;
				}
				?>
			</table>

		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>