<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once "share/oa_dec_cur_conv.php";
$referensi = Aplikasi_Referensi_Service::getInstance();


$ctrlFrm = new Zend_View();
?>
<? if(strtolower($this->jenisForm) == 'insert') {
		$namaForm = 'frmtambahuser'; 
		$jenisAksi = 'Tambah';
		$c_group = $this->c_group;
		}
    else if (strtolower($this->jenisForm) == 'update') {
		$namaForm = 'frmubahuser';  
		$jenisAksi = 'Ubah';
		$c_group = $this->detailUser['c_group'];
		}
	  else {	
	        $namaForm = 'frmhapususer';  
		$jenisAksi = 'Hapus';
		$c_group = $this->detailUser['c_group'];
		}
		
?>
		
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title"><? echo $jenisAksi;?> Data User</h2>
	    <div class="spacer"></div> 
		
		<form method="post" name="<? echo $namaForm;?>" id="<? echo $namaForm;?>">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
				    <td align="right" width="180">* Group :</td>
					<td>
					<?
						$jmlgroupList = count($this->groupList);
						$groupList['-'] = '--Pilih--';
						for ($i = 0; $i < $jmlgroupList; $i++) {
						    $groupList[$this->groupList[$i]->id] = (string)$this->groupList[$i]->n_nama;			 
						}
						
						$c_groupAtrib = array("id"=>"c_group", "tabindex"=>"17", "onchange"=>"javascript:pilihGroup($this->jenisForm);");
						echo $ctrlFrm->formSelect('c_group', $c_group, $c_groupAtrib, $groupList);

						?>
					</td>
				</tr>
				<tr>
				    <td align="right" width="180">* NIP :</td>
					<td>
						
						<?
						$user_idAttrib = array("size" => 50,"maxlength" => 50);
						echo $ctrlFrm->formText('user_id', $this->detailUser['user_id'], $user_idAttrib);
						
		?>
					</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* Nama :</td>
					<td>
						<?
						$nameAttrib = array("size" => 100,"maxlength" => 100);
						echo $ctrlFrm->formText('name', $this->detailUser['name'], $nameAttrib);
						?>
						
					</td>
				</tr>
				 <tr>
				    <td align="right" width="180">* Username :</td>
					<td>
						<?
						$usernameAttrib = array("size" => 50,"maxlength" => 50);
						echo $ctrlFrm->formText('username', $this->detailUser['username'], $usernameAttrib);
						echo $ctrlFrm->formHidden('id', $this->detailUser['id'], null);
						?>
						
					</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Status :</td>
					<td>
					<?
						//$jmlstatusList = count($this->statusList);
						$statusList['-'] = '--Pilih--';
						$statusList['1'] = 'Aktif';
						$statusList['0'] = 'Tidak Aktif';
						/*for ($i = 0; $i < $jmlstatusList; $i++) {
						    $statusList[$this->statusList[$i]->kd_status] = (string)$this->statusList[$i]->nm_status;			 
						}
						*/
						$kd_statusAtrib = array("id"=>"kd_status", "tabindex"=>"17");
						echo $ctrlFrm->formSelect('kd_status', $this->detailUser['kd_status'], $kd_statuspAtrib, $statusList);

						?>
					</td>
				</tr>
				
				
				<tr>
				    <td align="right" width="180">* Password :</td>
					<td>
						<?
						$passwordAttrib = array("size" => 20,"maxlength" => 20);
						echo $ctrlFrm->formPassword('password', '', $passwordAttrib);
						?>
					</td>
				</tr>
				<tr>
				    <td align="right" width="180">* Confirm Password :</td>
					<td>
						<input type="password"  size ="20" name="confirmPassword"  Value="<?php echo $password; ?>" id="confirmPassword" >
					</td>
				</tr>
				<tr>
				    <td></td>
				    <td>
						<div class="right">
							<input type="button" value="Batal" onClick="userlist();"> 
							<input type="reset" value="Ulangi"> 
							<input   type="submit" value="Simpan">
						</div>
					</td>
				</tr>
				<tr>
				    <td>* Harus Diisi</td>
				    <td></td>
				</tr>
			</table>
		</form>
	</div>
</div>