<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";
$referensi = Adm_Admuser_Service::getInstance();

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
		
$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">User</h2>
		<div class="search-panel">
			<form method="post" id="frmCariUser" name="frmCariUser">Kata Kunci :
				<?
				$kategoriCari = array("username" => "User",  "user_id" => "ID");
										
				echo $ctrlFrm->formSelect('kategoriCari', $this->kategoriCari, null, $kategoriCari);						
				?>
				<input type="text" name="carii">
				<?
			         $atribSubmit = array("onclick"=>"javascript:cariUser();");
			         echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
				?>
			</form>
		</div>
		<div class="space-line"></div>

		
		<fieldset class="fields"> 
			<div class="spacer"> </div>
			<? 
			
			$status = $this->hasil;
			$proses = $this->proses;
			$keterangan = $this->keterangan;
			
			$pesan->show_message($proses, $keterangan, "$status" ); ?>
			<div class="spacer"> </div>	
			
			<div class="add" title="Tambah Data" onClick="userForm('insert','');"></div> 

			<div class="blank"></div>
			
			
			<table id="sorter" class="sortable" cellspacing="1" cellpadding="2" border="0" align="center">
				<th width=5%  class="nosort">No</th> 
				<th width=10% class="sorted order2 sortable">User Name</th> 
				<th width=10% class="sorted order2 sortable">NIDN/NPM</th> 
				<th width=25% class="sorted order2 sortable">Nama</th> 
				<th width=10% class="nosort">Status Aktif</th>
				<th width=10% colspan="2"  class="nosort">Tindakan</th>
				
				<?
				if (count($this->userList) == 0){ 
				?>
					<tr class="event2"><td colspan="5"><font color="red">Data Tidak Ditemukan</font></td></tr>
				<?} else {
						
						
						foreach ($this->userList as $key => $val): 
						if ($key%2==0) { ?>
							<tr class="event">
						<? } else if ($key%2==1) { ?>
							<tr class="event2">
						<? } 
						$id = $this->escape($val['id']); 
						$username = $this->escape($val['username']); 
						$user_id = $this->escape($val['user_id']); 
						$kdStatus = $this->escape($val['kd_status']);
						$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
						
						$name = $this->escape($val['name']);
						// form Hidden 
						echo $ctrlFrm->formHidden('id', $id, null);
						
						?>
						
						<td class="clright"><? echo $noUrut;?>&nbsp;&nbsp;</td>
						<td class="clleft">&nbsp;<? echo $username;?></td>
						<td class="clleft">&nbsp;<? echo $user_id;?></td>
						<td class="clleft">&nbsp;<? echo $name;?></td>
						<? 
						if($kdStatus == '1') { $statusAktif = "checked";}
						else {$statusAktif = "";}
					
						?>
						<td align="center">
							<input type="checkbox" name="statusAktif_<? echo $key;?>" id="statusAktif_<? echo $key;?>" <? echo $statusAktif;?> value="<?echo $user_id;?>" onClick="ubahStatus(<?echo $key?>);">
						</td>
						
						<td><div onClick="userForm('update','<? echo $id;?>');" class="edit" title="Ubah Data"></div></td>
						<td><div class="delete" title="Hapus Data" onClick="userHapus('User', '<? echo $id; ?>')" ></td>
						
					
						</tr>
					<?
					endforeach;
				}
				?>
			</table>
			<?	
			$totalData = $this->totUserList;
			$modul = $this->basePath."/adm/user/userlist";
			
			echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $param1, $param2, $param3, $param4);		
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>