<script type="text/javascript">
function BukaWindows(){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = 800, popH = 600;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=0,scrollbars=yes');
}

function cariProvinsi(){
	$("#frmCariProvinsi").ajaxForm(frmCariProvinsi_opt);
}

var frmCariProvinsi_opt = {
		target : '#tableview',
		url: '<?php echo $this->basePath; ?>/provinsi/provinsi/provinsimenu',
		type: 'post', 
		resetForm: false
};

function provinsiMenu()
{
	var url = '<?php echo $this->basePath; ?>/provinsi/provinsi/provinsimenu';
	jQuery.get(url, function(data) {
		$("div#tableview").html(data);
	});
}

function provinsiForm(jenisForm, kode_provinsi)
{
	
	var url = '<?php echo $this->basePath; ?>/provinsi/provinsi/provinsiolahdata';
	
	var param = { jenisForm:jenisForm, kode_provinsi:kode_provinsi};
	jQuery.get(url, param, function(data) {
		jQuery("div#tableview").html(data);
		jQuery("#frmtambahprovinsi").ajaxForm(tambahProvinsi_opt);
		jQuery("#frmubahprovinsi").ajaxForm(ubahProvinsi_opt);		
		});
	
}

var tambahProvinsi_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/provinsi/provinsi/simpanprovinsi',
	beforeSubmit : function() {
		if (document.getElementById('kode_provinsi').value == ''){
			alert('Kode Provinsi harus Diisi');
			return false;
		}
		if (document.getElementById('provinsi').value == ''){
			alert('Nama Provinsi harus Diisi');
			return false;
		}
	},
	success: function(){doCount(5);},
	type: 'post', 
	resetForm: false
};

var ubahProvinsi_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/provinsi/provinsi/simpanprovinsiedit',
	beforeSubmit : function() {
		if (document.getElementById('kode_provinsi').value == ''){
			alert('Kode Provinsi harus Diisi');
			return false;
		}
		if (document.getElementById('provinsi').value == ''){
			alert('Nama Provinsi harus Diisi');
			return false;
		}
	},
	success: function(){doCount(5);},
	type: 'post', 
	resetForm: false
};

function Provinsihapus(param1, param2)
{ 
	
	if(ConfirmDelete(param1, param2))
	{	//alert("test");
		handler = '<?php echo $this->basePath; ?>/provinsi/provinsi/provinsihapus';
		var opt = {kode_provinsi : param2};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				doCount(5);
			 });
	}
}  
</script>