<?php
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";
require_once "penggunamenujs.phtml";
$referensi = Menu_Service::getInstance();

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
		
$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>

<div class="navlink">
<a href="#" class="home" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/home');">Halaman Utama</a>
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">Manajemen Pengguna</h2>
		<div class="search-panel">
			<form method="post" id="frmCariPengguna" name="frmCariPengguna">Kata Kunci :
				<?
				$kategoriCari = array("p.pengguna" => "Pengguna");
										
				echo $ctrlFrm->formSelect('kategoriCari', $this->kategoriCari, null, $kategoriCari);						
				?>
				<input type="text" name="carii">
				<?
			         $atribSubmit = array("onclick"=>"javascript:cariPengguna();");
			         echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
				?>
			</form>
		</div>
		<div class="space-line"></div>		
		<fieldset class="fields"> 
			<div class="spacer"> </div>
			<? 
			
			$status = $this->hasil;
			$proses = $this->proses;
			$keterangan = $this->keterangan;
			
			$pesan->show_message($proses, $keterangan, "$status" ); ?>
			<div class="spacer"> </div>	
			
			<div class="add" title="Tambah Data" onClick="penggunaForm('insert','');"></div> 

			<div class="blank"></div>
			
			
			<table id="sorter" class="sortable" cellspacing="1" cellpadding="2" border="0" align="center">
				<th width=5%  class="nosort">No</th> 
				<th width=15% class="sorted order2 sortable">Pengguna</th> 
				<th width=7% class="sorted order2 sortable">Password</th> 
				<th width=17% class="sorted order2 sortable">Instansi</th> 
				<th width=5% class="sorted order2 sortable">Level</th>  
				<th width=8% colspan="2"  class="nosort">Tindakan</th>
				
				<?php
					if (count($this->penggunaMenu) == 0){ 
				?>
					<tr class="event2"><td colspan="5"><font color="red">Data Tidak Ditemukan</font></td></tr>
				<?} else {					
					foreach ($this->penggunaMenu as $key => $val): 
					if ($key%2==0) { ?>
						<tr class="event">
					<? } else if ($key%2==1) { ?>
						<tr class="event2">
					<? } 
					$id = $this->escape($val['id']); 
					$pengguna = $this->escape($val['pengguna']); 				
					$password = $this->escape(md5($val['password'])); 				
					$KodeInstansi = $this->escape($val['KodeInstansi']); 				
					$Instansi = $this->escape($val['Instansi']); 				
					$level = $this->escape($val['level']); 					
					$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;	
					?>
					
					<td class="clright"><? echo $noUrut;?>&nbsp;&nbsp;</td>
					<td class="clleft">&nbsp;<? echo $pengguna;?></td>
					<td class="clleft">&nbsp;<? echo $password;?></td>									
					<td class="clleft">&nbsp;<? echo $Instansi;?></td>								
					<td class="clleft">&nbsp;<? echo $level;?></td>								
					<td><div onClick="penggunaForm('update','<? echo $id;?>');" class="edit" title="Ubah Data"></div></td>
					<td><div class="delete" title="Hapus Data" onClick="Penggunahapus('id', '<? echo $id; ?>')" ></td>
					</tr>
					<?
					endforeach;
				}
				?>
			</table>
			<?	
			$totalData = $this->totPengguna;
			$modul = $this->basePath."/pengguna/pengguna/penggunamenu";			
			echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $param1, $param2, $param3, $param4);		
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>